apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubectl.kubernetes.io/restartedAt: "2026-07-05T18:21:35-04:00"
    creationTimestamp: "2026-07-05T22:21:35Z"
    generateName: excalidraw-cbb698c9b-
    generation: 1
    labels:
      app: excalidraw
      pod-template-hash: cbb698c9b
    name: excalidraw-cbb698c9b-pp2mr
    namespace: excalidraw
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: excalidraw-cbb698c9b
      uid: bbc4b2b6-5083-4584-8dc3-dffe964748c7
    resourceVersion: "25545191"
    uid: 94cf21d9-07d7-4b82-8f34-eb0c6ba482ae
  spec:
    containers:
    - image: excalidraw/excalidraw:latest
      imagePullPolicy: Always
      name: excalidraw
      ports:
      - containerPort: 80
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-bg4qz
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: pi4-worker
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-bg4qz
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-07-05T22:21:46Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-07-05T22:21:36Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-07-05T22:21:46Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-07-05T22:21:46Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-07-05T22:21:36Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://789617cfce5f7468126dc226afd76b266a3473424c28f2aca3329e4f4099183b
      image: docker.io/excalidraw/excalidraw:latest
      imageID: docker.io/excalidraw/excalidraw@sha256:f7ee194addd607bf831d2af0f0a34463dd4225e426cf35199ef0b12a803398e9
      lastState: {}
      name: excalidraw
      ready: true
      resources: {}
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-07-05T22:21:46Z"
      user:
        linux:
          gid: 0
          supplementalGroups:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 6
          - 10
          - 11
          - 20
          - 26
          - 27
          uid: 0
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-bg4qz
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 192.168.1.222
    hostIPs:
    - ip: 192.168.1.222
    phase: Running
    podIP: 10.42.3.139
    podIPs:
    - ip: 10.42.3.139
    qosClass: BestEffort
    startTime: "2026-07-05T22:21:36Z"
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"excalidraw","namespace":"excalidraw"},"spec":{"ports":[{"nodePort":30905,"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"excalidraw"},"type":"NodePort"}}
    creationTimestamp: "2025-12-31T03:29:00Z"
    name: excalidraw
    namespace: excalidraw
    resourceVersion: "84822"
    uid: 7c9eb183-a1bf-4a88-944f-cbe30b84e111
  spec:
    clusterIP: 10.43.215.35
    clusterIPs:
    - 10.43.215.35
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 30905
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: excalidraw
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "3"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"excalidraw","namespace":"excalidraw"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"excalidraw"}},"template":{"metadata":{"labels":{"app":"excalidraw"}},"spec":{"containers":[{"image":"excalidraw/excalidraw:latest","name":"excalidraw","ports":[{"containerPort":80}]}]}}}}
    creationTimestamp: "2025-12-31T03:29:00Z"
    generation: 3
    name: excalidraw
    namespace: excalidraw
    resourceVersion: "25545205"
    uid: d8d77fc7-3d10-436d-8a29-540264ac1e89
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: excalidraw
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2026-07-05T18:21:35-04:00"
        creationTimestamp: null
        labels:
          app: excalidraw
      spec:
        containers:
        - image: excalidraw/excalidraw:latest
          imagePullPolicy: Always
          name: excalidraw
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2026-07-05T14:40:43Z"
      lastUpdateTime: "2026-07-05T14:40:43Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-12-31T03:29:00Z"
      lastUpdateTime: "2026-07-05T22:21:47Z"
      message: ReplicaSet "excalidraw-cbb698c9b" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 3
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "2"
    creationTimestamp: "2026-07-05T21:56:07Z"
    generation: 2
    labels:
      app: excalidraw
      pod-template-hash: 59d7f5dc86
    name: excalidraw-59d7f5dc86
    namespace: excalidraw
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: excalidraw
      uid: d8d77fc7-3d10-436d-8a29-540264ac1e89
    resourceVersion: "25545204"
    uid: d90debb4-306e-4058-90d2-85d13ce98592
  spec:
    replicas: 0
    selector:
      matchLabels:
        app: excalidraw
        pod-template-hash: 59d7f5dc86
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2026-07-05T17:56:07-04:00"
        creationTimestamp: null
        labels:
          app: excalidraw
          pod-template-hash: 59d7f5dc86
      spec:
        containers:
        - image: excalidraw/excalidraw:latest
          imagePullPolicy: Always
          name: excalidraw
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    observedGeneration: 2
    replicas: 0
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2025-12-31T03:29:00Z"
    generation: 2
    labels:
      app: excalidraw
      pod-template-hash: 94b776788
    name: excalidraw-94b776788
    namespace: excalidraw
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: excalidraw
      uid: d8d77fc7-3d10-436d-8a29-540264ac1e89
    resourceVersion: "25539835"
    uid: 2fba724a-1672-40c2-9c8d-9fa17eda0476
  spec:
    replicas: 0
    selector:
      matchLabels:
        app: excalidraw
        pod-template-hash: 94b776788
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: excalidraw
          pod-template-hash: 94b776788
      spec:
        containers:
        - image: excalidraw/excalidraw:latest
          imagePullPolicy: Always
          name: excalidraw
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    observedGeneration: 2
    replicas: 0
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "3"
    creationTimestamp: "2026-07-05T22:21:35Z"
    generation: 1
    labels:
      app: excalidraw
      pod-template-hash: cbb698c9b
    name: excalidraw-cbb698c9b
    namespace: excalidraw
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: excalidraw
      uid: d8d77fc7-3d10-436d-8a29-540264ac1e89
    resourceVersion: "25545194"
    uid: bbc4b2b6-5083-4584-8dc3-dffe964748c7
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: excalidraw
        pod-template-hash: cbb698c9b
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2026-07-05T18:21:35-04:00"
        creationTimestamp: null
        labels:
          app: excalidraw
          pod-template-hash: cbb698c9b
      spec:
        containers:
        - image: excalidraw/excalidraw:latest
          imagePullPolicy: Always
          name: excalidraw
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
kind: List
metadata:
  resourceVersion: ""
